language: node_js
node_js:
  - "12"
cache:
  directories:
  - node_modules
script:
  - npm install -g @angular/cli
  - npm install
  - ng build --base-href=/losowarka/
deploy:
  provider: script
  script: bash ./deployment/deploy.sh
  on:
    branch: master
