language: node_js
node_js:
  - "12"
cache:
  directories:
  - node_modules
script:
  - npm install -g @angular/cli
  - npm install
  - ng build --base-href=/wroclawjug-random-attendee/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
